services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: vitor
      POSTGRES_PASSWORD: shin1357
      POSTGRES_DB: social-network-db
    
  web:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"