# Generated by Django 6.0.3 on 2026-07-08 13:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0003_user_pic_url_alter_follow_id_alter_like_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="creation_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
